version: '3'

services:
  #app:
  #  build:
  #    context: .
  #  container_name: app
  #  tty: true
  #  depends_on:
  #    - db

  db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    

volumes:
  pgdata: {}